var files_dup =
[
    [ "camiseta.c", "camiseta_8c.html", "camiseta_8c" ],
    [ "camiseta.h", "camiseta_8h.html", "camiseta_8h" ],
    [ "db.c", "db_8c.html", "db_8c" ],
    [ "db.h", "db_8h.html", "db_8h" ],
    [ "estadisticas.c", "estadisticas_8c.html", "estadisticas_8c" ],
    [ "estadisticas.h", "estadisticas_8h.html", "estadisticas_8h" ],
    [ "export.c", "export_8c.html", "export_8c" ],
    [ "export.h", "export_8h.html", "export_8h" ],
    [ "export_all.c", "export__all_8c.html", "export__all_8c" ],
    [ "export_all.h", "export__all_8h.html", "export__all_8h" ],
    [ "export_all_mejorado.c", "export__all__mejorado_8c.html", "export__all__mejorado_8c" ],
    [ "export_all_mejorado.h", "export__all__mejorado_8h.html", "export__all__mejorado_8h" ],
    [ "export_camisetas_mejorado.c", "export__camisetas__mejorado_8c.html", "export__camisetas__mejorado_8c" ],
    [ "export_camisetas_mejorado.h", "export__camisetas__mejorado_8h.html", "export__camisetas__mejorado_8h" ],
    [ "export_lesiones_mejorado.c", "export__lesiones__mejorado_8c.html", "export__lesiones__mejorado_8c" ],
    [ "export_lesiones_mejorado.h", "export__lesiones__mejorado_8h.html", "export__lesiones__mejorado_8h" ],
    [ "import.h", "import_8h.html", "import_8h" ],
    [ "lesion.h", "lesion_8h.html", "lesion_8h" ],
    [ "menu.h", "menu_8h_source.html", null ],
    [ "models.h", "models_8h.html", "models_8h" ],
    [ "partido.h", "partido_8h.html", "partido_8h" ],
    [ "sqlite3.h", "sqlite3_8h_source.html", null ],
    [ "utils.c", "utils_8c.html", "utils_8c" ],
    [ "utils.h", "utils_8h.html", "utils_8h" ]
];